apiVersion: v1
data:
  typesBundle.json: "{\n  \"spec\": {\n    \"substrate-threefold\": {\n      \"types\":
    [\n        {\n          \"minmax\": [\n            9,\n            null\n          ],\n
    \         \"types\": {\n            \"Farm\": {\n              \"version\": \"u32\",\n
    \             \"id\": \"u32\",\n              \"name\": \"Vec<u8>\",\n              \"twinId\":
    \"u32\",\n              \"pricingPolicyId\": \"u32\",\n              \"certificationType\":
    \"CertificationType\",\n              \"publicIps\": \"Vec<PublicIP>\"\n            },\n
    \           \"PublicIP\": {\n              \"ip\": \"Vec<u8>\",\n              \"gateway\":
    \"Vec<u8>\",\n              \"contractId\": \"u64\"\n            },\n            \"Entity\":
    {\n              \"version\": \"u32\",\n              \"id\": \"u32\",\n              \"name\":
    \"Vec<u8>\",\n              \"accountId\": \"AccountId\",\n              \"country\":
    \"Vec<u8>\",\n              \"city\": \"Vec<u8>\"\n            },\n            \"Twin\":
    {\n              \"version\": \"u32\",\n              \"id\": \"u32\",\n              \"accountId\":
    \"AccountId\",\n              \"ip\": \"Vec<u8>\",\n              \"entities\":
    \"Vec<EntityProof>\"\n            },\n            \"EntityProof\": {\n              \"entityId\":
    \"u32\",\n              \"signature\": \"Vec<u8>\"\n            },\n            \"PublicConfig\":
    {\n              \"ipv4\": \"Vec<u8>\",\n              \"ipv6\": \"Vec<u8>\",\n
    \             \"gw4\": \"Vec<u8>\",\n              \"gw6\": \"Vec<u8>\",\n              \"domain\":
    \"Vec<u8>\"\n            },\n            \"Location\": {\n              \"longitude\":
    \"Vec<u8>\",\n              \"latitude\": \"Vec<u8>\"\n            },\n            \"Resources\":
    {\n              \"hru\": \"u64\",\n              \"sru\": \"u64\",\n              \"cru\":
    \"u64\",\n              \"mru\": \"u64\"\n            },\n            \"Interface\":
    {\n              \"name\": \"Vec<u8>\",\n              \"mac\": \"Vec<u8>\",\n
    \             \"ips\": \"Vec<Vec<u8>>\"\n            },\n            \"CertificationType\":
    {\n              \"_enum\": [\n                \"Diy\",\n                \"Certified\"\n
    \             ]\n            },\n            \"CertificationCodeType\": {\n              \"_enum\":
    [\n                \"Farm\",\n                \"Entity\"\n              ]\n            },\n
    \           \"CertificationCodes\": {\n              \"version\": \"u32\",\n              \"id\":
    \"u32\",\n              \"name\": \"Vec<u8>\",\n              \"description\":
    \"Vec<u8>\",\n              \"certificationCodeType\": \"CertificationCodeType\"\n
    \           },\n            \"Policy\": {\n              \"value\": \"u32\",\n
    \             \"unit\": \"Unit\"\n            },\n            \"Unit\": {\n              \"_enum\":
    [\n                \"Bytes\",\n                \"Kilobytes\",\n                \"Megabytes\",\n
    \               \"Gigabytes\",\n                \"Terrabytes\"\n              ]\n
    \           },\n            \"DiscountLevel\": {\n              \"_enum\": [\n
    \               \"None\",\n                \"Default\",\n                \"Bronze\",\n
    \               \"Silver\",\n                \"Gold\"\n              ]\n            },\n
    \           \"NameRegistration\": {\n              \"nameRegistrationId\": \"u64\",\n
    \             \"twinId\": \"u32\",\n              \"name\": \"Vec<u8>\"\n            },\n
    \           \"FarmingPolicy\": {\n              \"version\": \"u32\",\n              \"id\":
    \"u32\",\n              \"name\": \"Vec<u8>\",\n              \"cu\": \"u32\",\n
    \             \"su\": \"u32\",\n              \"nu\": \"u32\",\n              \"ipv4\":
    \"u32\",\n              \"timestamp\": \"u64\",\n              \"certificationType\":
    \"CertificationType\"\n            },\n            \"ContractBill\": {\n              \"contractId\":
    \"u64\",\n              \"timestamp\": \"u64\",\n              \"discountLevel\":
    \"DiscountLevel\",\n              \"amountBilled\": \"u128\"\n            },\n
    \           \"PalletStorageVersion\": {\n              \"_enum\": [\n                \"V1\",\n
    \               \"V2\",\n                \"V3\"\n              ]\n            },\n
    \           \"StorageVersion\": {\n              \"_enum\": [\n                \"V1Struct\",\n
    \               \"V2Struct\",\n                \"V3Struct\"\n              ]\n
    \           },\n            \"Address\": \"MultiAddress\",\n            \"LookupSource\":
    \"MultiAddress\",\n            \"BalanceOf\": \"Balance\",\n            \"Public\":
    \"[u8;32]\",\n            \"U16F16\": \"[u8; 4]\",\n            \"BufferIndex\":
    \"u32\",\n            \"VestingInfo\": {\n              \"locked\": \"Balance\",\n
    \             \"perBlock\": \"Balance\",\n              \"startingBlock\": \"BlockNumber\",\n
    \             \"tftPrice\": \"U16F16\",\n              \"lastReleasedBlock\":
    \"BlockNumber\"\n            },\n            \"StellarTransaction\": {\n              \"amount\":
    \"Balance\",\n              \"target\": \"MultiAddress\"\n            },\n            \"MintTransaction\":
    {\n              \"amount\": \"u64\",\n              \"target\": \"AccountId\",\n
    \             \"block\": \"BlockNumber\",\n              \"votes\": \"u32\"\n
    \           },\n            \"BurnTransaction\": {\n              \"block\": \"BlockNumber\",\n
    \             \"amount\": \"u64\",\n              \"target\": \"Vec<u8>\",\n              \"signatures\":
    \"Vec<StellarSignature>\",\n              \"sequenceNumber\": \"u64\"\n            },\n
    \           \"RefundTransaction\": {\n              \"block\": \"BlockNumber\",\n
    \             \"amount\": \"u64\",\n              \"target\": \"Vec<u8>\",\n              \"txHash\":
    \"Vec<u8>\",\n              \"signatures\": \"Vec<StellarSignature>\",\n              \"sequenceNumber\":
    \"u64\"\n            },\n            \"StellarSignature\": {\n              \"signature\":
    \"Vec<u8>\",\n              \"stellarPubkey\": \"Vec<u8>\"\n            },\n            \"Burn\":
    {\n              \"target\": \"AccountId\",\n              \"amount\": \"BalanceOf\",\n
    \             \"block\": \"BlockNumber\",\n              \"message\": \"Vec<u8>\"\n
    \           },\n            \"ValueStruct\": {\n              \"value\": \"U16F16\"\n
    \           },\n            \"AccountInfo\": \"AccountInfoWithProviders\",\n            \"Keys\":
    \"SessionKeys2\",\n            \"SessionKeys1\": \"(AccountId)\",\n            \"TermsAndConditions\":
    {\n              \"accountId\": \"AccountId\",\n              \"timestamp\": \"u64\",\n
    \             \"documentLink\": \"Vec<u8>\",\n              \"documentHash\":
    \"Vec<u8>\"\n            },\n            \"Validator\": {\n              \"validatorNodeAccount\":
    \"AccountId\",\n              \"stashAccount\": \"AccountId\",\n              \"description\":
    \"Vec<u8>\",\n              \"tfConnectId\": \"Vec<u8>\",\n              \"info\":
    \"Vec<u8>\",\n              \"state\": \"ValidatorRequestState\"\n            },\n
    \           \"ValidatorRequestState\": {\n              \"_enum\": [\n                \"Created\",\n
    \               \"Approved\",\n                \"Validating\"\n              ]\n
    \           },\n            \"PricingPolicy\": {\n              \"version\": \"u32\",\n
    \             \"id\": \"u32\",\n              \"name\": \"Vec<u8>\",\n              \"su\":
    \"Policy\",\n              \"cu\": \"Policy\",\n              \"nu\": \"Policy\",\n
    \             \"ipu\": \"Policy\",\n              \"uniqueName\": \"Policy\",\n
    \             \"domainName\": \"Policy\",\n              \"foundationAccount\":
    \"AccountId\",\n              \"certifiedSalesAccount\": \"AccountId\"\n            },\n
    \           \"ContractData\": {\n              \"_enum\": {\n                \"NodeContract\":
    \"NodeContract\",\n                \"NameContract\": \"NameContract\"\n              }\n
    \           },\n            \"NodeContract\": {\n              \"nodeId\": \"u32\",\n
    \             \"deploymentData\": \"Vec<u8>\",\n              \"deploymentHash\":
    \"Vec<u8>\",\n              \"publicIps\": \"u32\",\n              \"publicIpsList\":
    \"Vec<PublicIP>\"\n            },\n            \"NameContract\": {\n              \"name\":
    \"Vec<u8>\"\n            },\n            \"ContractBillingInformation\": {\n              \"previousNuReported\":
    \"u64\",\n              \"lastUpdated\": \"u64\",\n              \"amountUnbilled\":
    \"u64\"\n            },\n            \"ContractResources\": {\n              \"contractId\":
    \"u64\",\n              \"used\": \"Resources\"\n            },\n            \"NruConsumption\":
    {\n              \"contractId\": \"u64\",\n              \"timestamp\": \"u64\",\n
    \             \"window\": \"u64\",\n              \"nru\": \"u64\"\n            },\n
    \           \"Consumption\": {\n              \"contractId\": \"u64\",\n              \"timestamp\":
    \"u64\",\n              \"cru\": \"u64\",\n              \"sru\": \"u64\",\n              \"hru\":
    \"u64\",\n              \"mru\": \"u64\",\n              \"nru\": \"u64\"\n            }\n
    \         }\n        },\n        {\n          \"minmax\": [\n            9,\n
    \           27\n          ],\n          \"types\": {\n            \"Node\": {\n
    \             \"version\": \"u32\",\n              \"id\": \"u32\",\n              \"farmId\":
    \"u32\",\n              \"twinId\": \"u32\",\n              \"resources\": \"Resources\",\n
    \             \"location\": \"Location\",\n              \"country\": \"Vec<u8>\",\n
    \             \"city\": \"Vec<u8>\",\n              \"publicConfig\": \"Option<PublicConfig>\",\n
    \             \"created\": \"u64\",\n              \"farmingPolicyId\": \"u32\",\n
    \             \"interfaces\": \"Vec<Interface>\"\n            }  \n          }\n
    \       },\n        {\n          \"minmax\": [\n            9,\n            25\n
    \         ],\n          \"types\": {\n            \"Contract\": {\n              \"version\":
    \" u32\",\n              \"state\": \"ContractState\",\n              \"contractId\":
    \"u64\",\n              \"twinId\": \"u32\",\n              \"contractType\":
    \"ContractData\"\n            },\n            \"ContractState\": {\n              \"_enum\":
    {\n                \"Created\": null,\n                \"Deleted\": null,\n                \"OutOfFunds\":
    null\n              }\n            }\n          }\n        },\n        {\n          \"minmax\":
    [\n            25,\n            null\n          ],\n          \"types\": {\n            \"Contract\":
    {\n              \"version\": \" u32\",\n              \"state\": \"ContractState\",\n
    \             \"contractId\": \"u64\",\n              \"twinId\": \"u32\",\n              \"contractType\":
    \"ContractData\"\n            },\n            \"ContractState\": {\n              \"_enum\":
    {\n                \"Created\": null,\n                \"Deleted\": \"Cause\"\n
    \             }\n            },\n            \"Cause\": {\n              \"_enum\":
    [\n                \"CanceledByUser\",\n                \"OutOfFunds\"\n              ]\n
    \           }\n          }\n        },\n        {\n          \"minmax\": [\n            27,\n
    \           42\n          ],\n          \"types\": {\n            \"Node\": {\n
    \             \"version\": \"u32\",\n              \"id\": \"u32\",\n              \"farmId\":
    \"u32\",\n              \"twinId\": \"u32\",\n              \"resources\": \"Resources\",\n
    \             \"location\": \"Location\",\n              \"country\": \"Vec<u8>\",\n
    \             \"city\": \"Vec<u8>\",\n              \"publicConfig\": \"Option<PublicConfig>\",\n
    \             \"created\": \"u64\",\n              \"farmingPolicyId\": \"u32\",\n
    \             \"interfaces\": \"Vec<Interface>\",\n              \"certificationType\":
    \"CertificationType\"\n            }\n          }\n        },\n        {\n          \"minmax\":
    [\n            43,\n            null\n          ],\n          \"types\": {\n            \"Node\":
    {\n              \"version\": \"u32\",\n              \"id\": \"u32\",\n              \"farmId\":
    \"u32\",\n              \"twinId\": \"u32\",\n              \"resources\": \"Resources\",\n
    \             \"location\": \"Location\",\n              \"country\": \"Vec<u8>\",\n
    \             \"city\": \"Vec<u8>\",\n              \"publicConfig\": \"Option<PublicConfig>\",\n
    \             \"created\": \"u64\",\n              \"farmingPolicyId\": \"u32\",\n
    \             \"interfaces\": \"Vec<Interface>\",\n              \"certificationType\":
    \"CertificationType\",\n              \"secureBoot\": \"bool\",\n              \"virtualized\":
    \"bool\",\n              \"serialNumber\": \"Vec<u8>\"\n            }\n          }\n
    \       }\n      ]\n    }\n  }\n}"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: indexer-config
