{{- $fullName := include "processor.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "processor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: http
      targetPort: 4000
    - port: {{ .Values.promService.port }}
      name: http-prom
      targetPort: 44233
  selector:
    {{- include "processor.selectorLabels" . | nindent 4 }}